### PR TITLE
MPD UI draw optimise

### PR DESCRIPTION
**Pull request by Ollieollieolllie**

### CODE REVIEW

**Review by mattysmith22 — COMMENTED** [review]
Not sure how I feel about this. My concern is that there is a good chance that we are only optimising the still case, allowing a user's performance to be fine when on the ground, but as soon as they take off their aircraft will lag out as the system starts redrawing

**Comment by Ollieollieolllie** [comment]
yeah, its not a great solution, Im trying to look into more methods of optimizing the draw icons and uidrawpoint, this drawing function is a major component of the new mpds, and it's a heavy hitter atm

**Comment by mattysmith22** [comment]
Do we know what part of the drawing is expensive? Knowing so may help us optimise

**Comment by mattysmith22** [comment]
I have had a couple ideas about optimisations, namely:

1) only doing the `ctrlSetText` when required, checking with an if statement beforehand
2) constructing each point in a `CT_CONTROLS_GROUP` and then moving that around, making it so that once one is created, moving it around is a lot cheaper
3) tied in with 2, doing something similar to this with all the attributes other than position so that once a point is created, we don't need to update the stuff inside (icons, positioning of text etc. etc.) each time

**Comment by mattysmith22** [comment]
Are you good if I close this PR and the raise an issue with the suggestions above for future exploration?

**Comment by Ollieollieolllie** [comment]
review at a later date
#587

**Pull request closed without merging**
